### ISSUE TITLE
Unable to Tunnel

### ISSUE THREAD

**Issue by thatMacAdmin** [yusufhm/rport-image#1]
Hi,

First thanks for your amazing example! I was able to setup rport in my cluster with traefik using your examples. However, it's not clear how I would setup the service and traefik for tunnels. Any thoughts or examples on how you accomplished it?

**Comment by itsupport-s2i** [comment]
same question. how to expose tunnel's ports

**Comment by yusufhm** [comment]
Hi @thatMacAdmin & @itsupport-s2i, it's been a while since I've used it now, but from what I remember you can't use Traefik for this; I believe I manually created dedicated LoadBalancer services for each host I wanted to access.

Here's an example:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: rport-vnc
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: rport
  ports:
    - name: vnc
      protocol: TCP
      port: 23389
```

This worked for me because I had very few clients - if you've got more, you might have to automate it in some way.

**Comment by yusufhm** [comment]
I also had an IngressRoute, although I'm not quite sure anymore why that was required:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: rport-vnc
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ui.rport.{domain}`)
      kind: Rule
      services:
        - name: rport-vnc
          port: 23389
  tls:
    secretName: rport-tls-secret
```
